version: '3.7'
services:
  pssql:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=PatientDb
      - POSTGRES_PASSWORD=P@ssw0rd

  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
