apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dmakeroam
configMapGenerator:
- name: appsettings
  files:
  - appsettings.Production.json
generatorOptions:
  disableNameSuffixHash: true